<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2021/10/28 11:48:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=mariadb;port=3306;dbname=bitnami_orangehrm;charset=utf8mb4',
  'username' => 'bn_orangehrm',
  'password' => NULL,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
