<?php
// auto-generated by sfSecurityConfigHandler
// date: 2021/10/28 11:48:47
$this->security = array (
  'viewbuzzimage' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
